-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.accounts
(
    id serial NOT NULL,
    account_number bigint NOT NULL,
    account_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    balance numeric(15, 2) NOT NULL,
    user_id integer NOT NULL,
    CONSTRAINT accounts_pkey PRIMARY KEY (id),
    CONSTRAINT accounts_account_number_key UNIQUE (account_number)
);

CREATE TABLE IF NOT EXISTS public.transactions
(
    id serial NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    amount numeric(15, 2) NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    source_account bigint NOT NULL,
    target_account bigint,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    cpf character varying(11) COLLATE pg_catalog."default" NOT NULL,
    birth_date date NOT NULL,
    phone character varying(11) COLLATE pg_catalog."default" NOT NULL,
    password character varying(6) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_cpf_key UNIQUE (cpf)
);

ALTER TABLE IF EXISTS public.accounts
    ADD CONSTRAINT accounts_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_source_account FOREIGN KEY (source_account)
    REFERENCES public.accounts (account_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.transactions
    ADD CONSTRAINT fk_target_account FOREIGN KEY (target_account)
    REFERENCES public.accounts (account_number) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;